<?php

namespace Tests\Unit;

use CodeIgniter\Events\Events;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\FeatureTestTrait;

/**
 * Validates Phase 3D execution ordering:
 * Proves that for every rate-limited authentication endpoint, the Throttle filter
 * executes in CodeIgniter's request lifecycle strictly BEFORE:
 *   - controller instantiation and execution
 *   - password_hash / password_verify
 *   - database queries
 *   - token generation
 *   - email dispatch preparation
 */
class ThrottleExecutionOrderTest extends CIUnitTestCase
{
    use FeatureTestTrait;

    protected function setUp(): void
    {
        parent::setUp();
        unset($_SERVER['REMOTE_ADDR']);
        service('superglobals')->setServer('REMOTE_ADDR', '0.0.0.0');
        service('cache')->clean();
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        unset($_SERVER['REMOTE_ADDR']);
        service('cache')->clean();
    }

    /**
     * Helper to verify that breaching the rate limit on a specific auth endpoint
     * short-circuits the request pipeline, returning 429 with Retry-After, and
     * prevents any controller execution or database queries.
     */
    private function assertEndpointThrottledBeforeController(string $uri, array $payload): void
    {
        service('cache')->clean();

        $cleanUri = ltrim($uri, '/');
        // Pre-fill the throttle cache bucket to simulate quota exhaustion (limit 30)
        // CodeIgniter FeatureTestTrait uses 0.0.0.0 and includes indexPage in URI path
        $bucket = 'throttle_' . md5('0.0.0.0/index.php/' . $cleanUri);
        service('cache')->save($bucket, 30, 60);

        // Instrument events to track controller instantiation and DB queries
        $executedQueries   = 0;
        $controllerEntered = false;

        Events::on('DBQuery', static function () use (&$executedQueries) {
            $executedQueries++;
        });

        Events::on('post_controller_constructor', static function () use (&$controllerEntered) {
            $controllerEntered = true;
        });

        // Dispatch request through CodeIgniter's full HTTP pipeline
        $result = $this->withHeaders([
            'Content-Type' => 'application/json',
            'Accept'       => 'application/json',
        ])->post($cleanUri, $payload);

        // 1. Must return HTTP 429 Too Many Requests
        $result->assertStatus(429);

        // 2. Must contain Retry-After: 60 header
        $result->assertHeader('Retry-After', '60');

        // 3. Response body must be RFC 9457 problem payload generated by Throttle filter
        $body = json_decode($result->response()->getBody(), true);
        $this->assertSame('too_many_requests', $body['reason'] ?? null);
        $this->assertSame(429, $body['status'] ?? null);
        $this->assertSame(60, $body['retry_after'] ?? null);

        // 4. Controller must NOT have been instantiated or executed
        $this->assertFalse($controllerEntered, "Controller must NOT be instantiated when Throttle filter blocks {$uri}.");

        // 5. ZERO database queries must have executed during this request
        $this->assertSame(0, $executedQueries, "Zero DB queries must execute when Throttle filter blocks {$uri}.");
    }

    public function testThrottlePrecedesControllerOnRegister(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/register', [
            'name'     => 'Attack User',
            'email'    => 'attacker@example.com',
            'password' => 'ExpensivePassword123!',
            'org_name' => 'Attack Corp',
        ]);
    }

    public function testThrottlePrecedesControllerOnLogin(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/login', [
            'email'    => 'target@example.com',
            'password' => 'GuessedPassword123!',
        ]);
    }

    public function testThrottlePrecedesControllerOnOtpRequest(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/otp/request', [
            'phone' => '0771234567',
        ]);
    }

    public function testThrottlePrecedesControllerOnOtpVerify(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/otp/verify', [
            'phone' => '0771234567',
            'code'  => '123456',
        ]);
    }

    public function testThrottlePrecedesControllerOnForgotPassword(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/forgot-password', [
            'email' => 'victim@example.com',
        ]);
    }

    public function testThrottlePrecedesControllerOnResetPassword(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/reset-password', [
            'token'    => bin2hex(random_bytes(32)),
            'password' => 'NewPassword123!',
        ]);
    }

    public function testThrottlePrecedesControllerOnVerifyEmail(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/verify-email', [
            'token' => bin2hex(random_bytes(24)),
        ]);
    }

    public function testThrottlePrecedesControllerOnResendVerification(): void
    {
        $this->assertEndpointThrottledBeforeController('api/v1/auth/resend-verification', [
            'email' => 'pending@example.com',
        ]);
    }
}
